version: '3.8'
services:
  backend:
    build: ./LavoroBack
    image: 192.168.50.4:8083/nodemongoapp:5.0
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db